POST http://localhost:8080/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE0NzE4OTQsImlhdCI6MTc1MTQ3MDk5NCwicm9sZXMiOlsic3VwZXIgYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlo1V1dXTlRTN1c2M0EzSzJFWEpQQUVBIiwidXNlcl9pZCI6IjAxSlozTjFFTUJZVDRYVDE5MVpaQzU4R1M3In0.EL4C7oAPXAeukamcREyi-_ygBIkwv533U0KHMmXZh_U

###
GET http://localhost:8080/api/coba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE0NzE4OTQsImlhdCI6MTc1MTQ3MDk5NCwicm9sZXMiOlsic3VwZXIgYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlo1V1dXTlRTN1c2M0EzSzJFWEpQQUVBIiwidXNlcl9pZCI6IjAxSlozTjFFTUJZVDRYVDE5MVpaQzU4R1M3In0.EL4C7oAPXAeukamcREyi-_ygBIkwv533U0KHMmXZh_U
Accept: application/json

### Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "identifier": "superadmin",
  "password": "superadmin"
}

### register
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "irawankilmer",
  "email": "irawankilmer@gmail.com",
  "password": "irawankilmer@gmail.com"
}