POST http://localhost:8080/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE1Mzk0MDksImlhdCI6MTc1MTUzODUwOSwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbInRhbXUiXSwidG9rZW5fdmVyc2lvbiI6IjAxSlo3WDk5Vk5FUlNaUDk1WUdINFM0Qk5QIiwidXNlcl9pZCI6IjAxSlo3WDFCWUhIM0NSUzFKMEJHUjhDN1RSIn0.RNJrS3t5myZi1tfo1y1WjA1jYkonmY0sirsy-2qRswk

###
GET http://localhost:8080/api/coba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE1Mzk0MDksImlhdCI6MTc1MTUzODUwOSwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbInRhbXUiXSwidG9rZW5fdmVyc2lvbiI6IjAxSlo3WDk5Vk5FUlNaUDk1WUdINFM0Qk5QIiwidXNlcl9pZCI6IjAxSlo3WDFCWUhIM0NSUzFKMEJHUjhDN1RSIn0.RNJrS3t5myZi1tfo1y1WjA1jYkonmY0sirsy-2qRswk
Accept: application/json

###
GET http://localhost:8080/api/coba-verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE1Mzk0MDksImlhdCI6MTc1MTUzODUwOSwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbInRhbXUiXSwidG9rZW5fdmVyc2lvbiI6IjAxSlo3WDk5Vk5FUlNaUDk1WUdINFM0Qk5QIiwidXNlcl9pZCI6IjAxSlo3WDFCWUhIM0NSUzFKMEJHUjhDN1RSIn0.RNJrS3t5myZi1tfo1y1WjA1jYkonmY0sirsy-2qRswk
Accept: application/json

### Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "identifier": "irawankilmer",
  "password": "irawankilmer@gmail.com"
}

### register
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "irawankilmer",
  "email": "irawankilmer@gmail.com",
  "password": "irawankilmer@gmail.com"
}