###
POST http://localhost:8080/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE3MDUwNzAsImlhdCI6MTc1MTcwNDE3MCwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiIwMUpaQ1Y4VlowQkgwWlBUQ0U1NVMwSjk3TiIsInVzZXJfaWQiOiIwMUpaQ1NLQjQzS01HMlNEQjBGQ0Q0SDNBRiJ9.OQ-pYVr-zpzv2olMuNjROgIkzJumTTTV7s5OFD7Qh_k

###
GET http://localhost:8080/api/coba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE3MDUwNzAsImlhdCI6MTc1MTcwNDE3MCwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiIwMUpaQ1Y4VlowQkgwWlBUQ0U1NVMwSjk3TiIsInVzZXJfaWQiOiIwMUpaQ1NLQjQzS01HMlNEQjBGQ0Q0SDNBRiJ9.OQ-pYVr-zpzv2olMuNjROgIkzJumTTTV7s5OFD7Qh_k
Accept: application/json

###
GET http://localhost:8080/api/coba-verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE3MDUwNzAsImlhdCI6MTc1MTcwNDE3MCwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiIwMUpaQ1Y4VlowQkgwWlBUQ0U1NVMwSjk3TiIsInVzZXJfaWQiOiIwMUpaQ1NLQjQzS01HMlNEQjBGQ0Q0SDNBRiJ9.OQ-pYVr-zpzv2olMuNjROgIkzJumTTTV7s5OFD7Qh_k
Accept: application/json

### Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "identifier": "superadmin",
  "password": "superadmin"
}

### register
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "irawankilmer",
  "email": "irawankilmer@gmail.com",
  "password": "irawankilmer@gmail.com"
}