GET http://localhost:8080/api/email-verification?token=ef19568a03fb3539bde32e396068a8380aa567a53d876cbe60f31bf88e0e53f1
Accept: application/json

###
### GET request to example server
GET https://examples.http-client.intellij.net/get
  ?generated-in=GoLand

###