GET http://localhost:8080/api/email-verification?token=15af1e3fa1413c2c75744975b381053db029eda0933e6f84935e7a711de94037
Accept: application/json

###
### GET request to example server
GET https://examples.http-client.intellij.net/get
  ?generated-in=GoLand

###