### Coba roleMiddleware super admin
GET http://localhost:8080/api/coba-super-admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAyNDgwMjMsImlhdCI6MTc1MDE2MTYyMywicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlhZVzYySk0xN0Y2TTdCRlRaWlg3NkNGIiwidXNlcl9pZCI6IjAxSlhZVDlZWjRLUjYzRFEzOVo2OE4zN1JLIn0.oN18_8jFwJDqGM1yzeQFkfX7hUXj5Bq-HYj-zeacDA4

### Coba Auth
GET http://localhost:8080/api/coba-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAyNDgwMjMsImlhdCI6MTc1MDE2MTYyMywicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlhZVzYySk0xN0Y2TTdCRlRaWlg3NkNGIiwidXNlcl9pZCI6IjAxSlhZVDlZWjRLUjYzRFEzOVo2OE4zN1JLIn0.oN18_8jFwJDqGM1yzeQFkfX7hUXj5Bq-HYj-zeacDA4

### Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "identifier": "super-admin-1",
    "password": "super-admin-1"
}

### Registrasi
POST http://localhost:8080/api/register
Content-Type: application/json

{
    "username": "tamu-saja",
    "email": "tamu-saja@gmail.com",
    "password": "tamu-saja"
}

### Logout
POST http://localhost:8080/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAyNDgwMjMsImlhdCI6MTc1MDE2MTYyMywicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlhZVzYySk0xN0Y2TTdCRlRaWlg3NkNGIiwidXNlcl9pZCI6IjAxSlhZVDlZWjRLUjYzRFEzOVo2OE4zN1JLIn0.oN18_8jFwJDqGM1yzeQFkfX7hUXj5Bq-HYj-zeacDA4
