### Ambil semua data
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAyNTQ4ODEsImlhdCI6MTc1MDE2ODQ4MSwicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlhaMlFCQjdQV0tGNjNYM0ZDTTBWQ0M0IiwidXNlcl9pZCI6IjAxSlhZVDlZWjRLUjYzRFEzOVo2OE4zN1JLIn0.2z_u1gk1tuc1AutosiWi3xokIGIOadxXWGwCV-0wj7o

### Create
POST http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAyNTQ4ODEsImlhdCI6MTc1MDE2ODQ4MSwicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlhaMlFCQjdQV0tGNjNYM0ZDTTBWQ0M0IiwidXNlcl9pZCI6IjAxSlhZVDlZWjRLUjYzRFEzOVo2OE4zN1JLIn0.2z_u1gk1tuc1AutosiWi3xokIGIOadxXWGwCV-0wj7o
Content-Type: application/json

{
    "username": "editor-saja",
    "email": "editor-saja@gmail.com",
    "password": "editor-saja",
    "role_ids": ["01JXYT9YZ4Y728VWB60BNCAYD8"]
}
###

### Ambil data BY ID
GET http://localhost:8080/api/users/01JXYV40T83BVAC9TYG3A7MJ7T
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAyNTQ4ODEsImlhdCI6MTc1MDE2ODQ4MSwicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlhaMlFCQjdQV0tGNjNYM0ZDTTBWQ0M0IiwidXNlcl9pZCI6IjAxSlhZVDlZWjRLUjYzRFEzOVo2OE4zN1JLIn0.2z_u1gk1tuc1AutosiWi3xokIGIOadxXWGwCV-0wj7o

### Update Data
PUT http://localhost:8080/api/users/01JY12SQHBP2TJGG6CSG7ZANTY
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAyNTQ4ODEsImlhdCI6MTc1MDE2ODQ4MSwicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlhaMlFCQjdQV0tGNjNYM0ZDTTBWQ0M0IiwidXNlcl9pZCI6IjAxSlhZVDlZWjRLUjYzRFEzOVo2OE4zN1JLIn0.2z_u1gk1tuc1AutosiWi3xokIGIOadxXWGwCV-0wj7o
Content-Type: application/json

{
    "username": "tamu-beserta-penulis",
    "email": "tamu-beserta-penulis@gmail.com",
    "role_ids": ["01JXYT9YZ4Y728VWB60BNCAYD8"]
}
###

### Delete data
DELETE http://localhost:8080/api/users/01JY0TS5HBGPEQAJSBFETVVYKN
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAyNTQ4ODEsImlhdCI6MTc1MDE2ODQ4MSwicm9sZXMiOlsic3VwZXItYWRtaW4iXSwidG9rZW5fdmVyc2lvbiI6IjAxSlhaMlFCQjdQV0tGNjNYM0ZDTTBWQ0M0IiwidXNlcl9pZCI6IjAxSlhZVDlZWjRLUjYzRFEzOVo2OE4zN1JLIn0.2z_u1gk1tuc1AutosiWi3xokIGIOadxXWGwCV-0wj7o