CREATE TABLE users (
    id VARCHAR(26) NOT NULL UNIQUE PRIMARY KEY,
    username VARCHAR(125) NOT NULL UNIQUE,
    email VARCHAR(125) NOT NULL UNIQUE,
    password VARCHAR(125) NOT NULL,
    token_version VARCHAR(26),
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    id VARCHAR(26) NOT NULL UNIQUE PRIMARY KEY,
    name VARCHAR(125) NOT NULL UNIQUE,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id VARCHAR(26),
    role_id VARCHAR(26),
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE
);