basePath: /
definitions:
  request.AuthLoginRequest:
    properties:
      identifier:
        type: string
      password:
        type: string
    required:
    - identifier
    - password
    type: object
  request.AuthRegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  request.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      role_ids:
        items:
          type: string
        type: array
      username:
        type: string
    required:
    - email
    - password
    - role_ids
    - username
    type: object
  request.UpdateUserRequest:
    properties:
      email:
        type: string
      role_ids:
        items:
          type: string
        type: array
      username:
        type: string
    required:
    - email
    - role_ids
    - username
    type: object
  response.AuthSwaggerResponse:
    properties:
      code:
        type: integer
      data:
        type: string
      message:
        type: string
    type: object
  response.RoleResponse:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  response.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      roles:
        items:
          $ref: '#/definitions/response.RoleResponse'
        type: array
      username:
        type: string
    type: object
  response.UserSwaggerResponse:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/response.UserResponse'
        type: array
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Auth system
  title: Auth - REST API Docs
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AuthLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.AuthSwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.AuthSwaggerResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.AuthSwaggerResponse'
      summary: Login
      tags:
      - Auth
  /api/auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.AuthSwaggerResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.AuthSwaggerResponse'
      security:
      - BearerAuth: []
      summary: Logout current user
      tags:
      - Auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AuthRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.AuthSwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.AuthSwaggerResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.AuthSwaggerResponse'
      summary: Register new user
      tags:
      - Auth
  /api/auth/users:
    get:
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
      security:
      - BearerAuth: []
      summary: Get all users with pagination
      tags:
      - Users
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
      security:
      - BearerAuth: []
      summary: Create a new user
      tags:
      - Users
  /api/auth/users/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
      security:
      - BearerAuth: []
      summary: Delete user by ID
      tags:
      - Users
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
      security:
      - BearerAuth: []
      summary: Get user by ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated user data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.UserSwaggerResponse'
      security:
      - BearerAuth: []
      summary: Update user by ID
      tags:
      - Users
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
